"""Agent output schemas for question generation and follow-up suggestions."""

from typing import List, Literal, Optional
from pydantic import BaseModel, Field, field_validator


class GeneratedQuestion(BaseModel):
    """
    A question generated by the Question Generation Agent.
    Must pass validation before being shown to the interviewer.
    """

    question: str = Field(..., min_length=10, max_length=1000)
    topic: str = Field(..., min_length=2, max_length=100)
    difficulty: Literal["easy", "medium", "hard"]
    type: Literal["technical", "behavioral", "system_design", "conceptual", "situational"]
    rationale: str = Field(..., min_length=10, max_length=500)
    expected_signals: List[str] = Field(default_factory=list, max_length=8)

    @field_validator("expected_signals")
    @classmethod
    def validate_signals(cls, v: List[str]) -> List[str]:
        return [s.strip() for s in v if s.strip()]


class FollowUpSuggestion(BaseModel):
    """
    A follow-up question suggested by the Follow-Up Agent based on candidate's answer.
    This is a SUGGESTION — interviewers must explicitly choose to ask it.
    """

    question: str = Field(..., min_length=10, max_length=1000)
    reason: str = Field(..., min_length=10, max_length=500)
    target_skill: str = Field(..., min_length=2, max_length=100)
    difficulty: Literal["easy", "medium", "hard"]
    priority: Literal["low", "medium", "high"]

    # Confidence from 0.0 to 1.0
    confidence: float = Field(..., ge=0.0, le=1.0)

    # Evidence references grounding this suggestion in actual interview data
    evidence: List[str] = Field(default_factory=list, max_length=5)
